### ISSUE TITLE
(8.x) CJS support dropped?

### ISSUE THREAD

**Issue by PapiOphidian** [Borewit/music-metadata#1218]
When trying to import this mod with NodeRequire, node throws an error saying that you cannot import this esm module using require. Specification of main fields in the package.json also leads to some "funky" behaviour. In my use case, I was unable to type cast properly using the import(…) statement. Just more of a question rather than a feature request or call to action as I *could* migrate my project to esm, but I sway more towards favoring cjs.

**Comment by Borewit** [comment]
Correct, music-metadata switched to ESM since version 8, as clearly written in the [README](https://github.com/Borewit/music-metadata#compatibility) and the [release notes of version 8](https://github.com/Borewit/music-metadata/releases/tag/v8.0.0).

Just use version 7 if you prefer to stick with CJS. I will not advocate ESM is all good. It's a super painful transition, the lack of backward compatibility is very disappointing. I hope on the long run helps to close the gap between Node.js and browser environment. It is possible to import ESM in CJS project, but not via require. You need load ESM module async.

**Comment by xfl03** [comment]
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
```

How can I use version 8 in TypeScript with `tsc`?

> Correct, music-metadata switched to ESM since version 8, as clearly written in the [README](https://github.com/Borewit/music-metadata#compatibility) and the [release notes of version 8](https://github.com/Borewit/music-metadata/releases/tag/v8.0.0).
> 
> Just use version 7 if you prefer to stick with CJS. I will not advocate ESM is all good. It's a super painful transition, the lack of backward compatibility is very disappointing. I hope on the long run helps to close the gap between Node.js and browser environment. It is possible to import ESM in CJS project, but not via require. You need load ESM module async.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
```

How can I use version 8 in TypeScript with `tsc`?

**Comment by Borewit** [comment]
See notes of [Sindresorhus CJS to ESM migration](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

The [music-metadata tsconfig.json](https://github.com/Borewit/music-metadata/blob/master/tsconfig.json) probably works for you as well. But that assumes you migrate your project to ESM. Running your project as CJS, with TypeScript and trying to import the ESM version of music-metadata is asking for trouble.

**Comment by Borewit** [comment]
Glad you like it @Jelmerro . As long ESM is not the best solution for the majority of users, I will keep doing updates on the CJS versions, especially security and bug fixes. Thank you for sharing you concern, I will keep it in mind.

**Comment by Jelmerro** [comment]
Really happy to hear you are not dropping support for it. Just one more question, would it be possible to have a separate [dist-tag](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag) on npm for cjs releases, so that cjs users have a single tag to point to instead of "latest" e.g. "cjs"? If so, that would be amazing.

**Comment by Borewit** [comment]
> would it be possible to have a separate [dist-tag](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag) on npm for cjs release

Done, I hope I don't forget to re-assign it next 7.x release.
