### ISSUE TITLE
Fails to analyze some m4a files

### ISSUE THREAD

**Issue by ash67** [Borewit/music-metadata#1390]
**Bug description**
Some m4a files return `Error message: End-Of-Stream`. Even though the file plays just file. I tried different methods like `parseFile`,  `parseBuffer` and `parseStream`. But they all fail at the `readBuffer` function inside the `strtok3` library.

I am running `7.13.0` common js version in node env.

**Expected behavior**
Any m4a file should work.

**Audio file demonstrating the problem**
If applicable, please drag and drop the __zipped__ audio file(s) which caused the problem into the bug report.
Please create additional issues if you experience different problems for each file.

Here is the error stack. 
```
 at FileTokenizer.readBuffer (../../node_modules/strtok3/lib/FileTokenizer.js:25:13)
      at FileTokenizer.readToken (../../node_modules/strtok3/lib/AbstractTokenizer.js:25:17)
      at Function.readAtom (../../node_modules/music-metadata/lib/mp4/Atom.js:19:20)
      at Atom.readAtoms (../../node_modules/music-metadata/lib/mp4/Atom.js:38:24)
      at Function.readAtom (../../node_modules/music-metadata/lib/mp4/Atom.js:27:5)
      at MP4Parser.parse (../../node_modules/music-metadata/lib/mp4/MP4Parser.js:237:24)
      at parse (../../node_modules/music-metadata/lib/ParserFactory.js:38:3)
      at parseFile (../../node_modules/music-metadata/lib/index.js:46:12)
```

For some reason `bytesRead` at this [line](https://github.com/Borewit/strtok3/blob/master/lib/FileTokenizer.ts#L23) was 0. Not sure why.

If it helps, here is the file metadata that was generated via `ffmpeg` in terminal

```
major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2022-10-28T11:44:43.000000Z
    com.android.version: 10
  Duration: 00:02:04.80, start: 0.000000, bitrate: 150 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 148 kb/s (default)
    Metadata:
      creation_time   : 2022-10-28T11:44:43.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
```

**Comment by Borewit** [comment]
I need a sample to analyze the issue.

**Comment by sam-serenade** [comment]
> I need close this issue @ash67 without any way to reproduce this issue.

Hi Borewit, I am afraid that we cannot share the file on a public forum, but if you can provide contact details I will be happy to send it direct to you. thanks. Sam

**Comment by Borewit** [comment]
Understood @sam-serenade, posting it to <myGitHubUserName>@xs4all.nl will do the trick.

**Comment by Borewit** [comment]
Investigating the sample provided by @sam-serenade 

For some reason it seems that the `meta` ATOM is lacking the 4 bytes padding bytes.

I traced the long history of this 4 bytes padding, and it has been present since the very beginning when MP4 support was added in musicmetadata in 2010:

https://github.com/Borewit/music-metadata/blob/b4e6a268f6e7ac17bcd9e07791190d4330c3fb4e/lib/id3/id4.js#L31

which corresponds in today's code with:

https://github.com/Borewit/music-metadata/blob/7cdebd1ca61411f3bb8bf7ae1d69a916ff317222/lib/mp4/Atom.ts#L68-L69

Related documentation: https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW8, in which I can not find anything about this 4 padding bytes.

What about other MP4 parsers?

Let's check [Mutagen](https://github.com/quodlibet/mutagen):

I am not much of Python programmer, but it seems like it skipping those 4 padding bytes as well:
- https://github.com/quodlibet/mutagen/blob/a361ed3f838b77fe3b9c9b025b9802b47b010bc4/mutagen/mp4/_atom.py#L16
- https://github.com/quodlibet/mutagen/blob/a361ed3f838b77fe3b9c9b025b9802b47b010bc4/mutagen/mp4/_atom.py#L72

Although I have not find any solid proof, I suspect the provided sample is encoded incorrectly.

**Comment by Borewit** [comment]
Workaround to parse this file: [issue-1390-workaround](https://github.com/Borewit/music-metadata/tree/issue-1390-workaround)

**Comment by ash67** [comment]
@Borewit Apologies for the late response! It looks like your workaround works! Thanks so much!

**Comment by yuezhaoBJ** [comment]
Have the same issue with an audio file with the following metadata. The [issue-1390-workaround](https://github.com/Borewit/music-metadata/tree/issue-1390-workaround) also works well in my situation. May I ask when we should expect the workaround merged?

```
codec: 'MPEG-4/AAC'
container: 'mp42/isom'
```
