### ISSUE TITLE
Tag reading failure for some M4A files

### ISSUE THREAD

**Issue by LudekStoklasa** [Borewit/music-metadata#151]
Hi, I wonder why [this M4A](https://www.dropbox.com/s/cf2qwx6toy9pnfw/2%20-%20Angels%20and%20Airwaves%20-%20Distraction.m4a?dl=0) file fails to read tag completely?

Tested also in iTunes, Windows Explorer, Windows Media Player, MediaMonkey, AIMP and all the apps read the tag just fine.

**Comment by Borewit** [comment]
Thanks for reporting the issue @LudekStoklasa, I will look into it.

**Comment by Borewit** [comment]
I find it interesting that those applications have no issues.
But is not just music-metadata, because these application (which are very reliable in my experience) are not able to extract metadata neither:
1. foobar2000
2. Mp3tag

I concur iTunes reads the tags just fine.

If I look into the file, it really looks to me the file contains an encoding mistake.

At position 63592 the length of the 'mdat' atom is stored, which is 14065434 (`00 D6 9F 1A`).
However I think the length should be 14065439 (+5), the `1A` should be `1F`.
I gave it try, then it will read the following 'mean' atom correctly and will parse just fine until the end of the file.

Under the assumption it is encoding error, I don't directly see how I go around it.

**Comment by Borewit** [comment]
I found something, to be continued...

**Comment by Borewit** [comment]
Thanks to [this too]l(https://www.bento4.com/downloads/) I was able to figure out how the other indented structure looked like:
 ````
[ftyp] size=8+16
  major_brand = mp42
  minor_version = 0
  compatible_brand = mp42
  compatible_brand = isom
[free] size=8+63559
[mdat] size=8+14065426
[-...] size=8+67  <=== which is a dash with 0x00, 0x00, 0x00. Apparently that should be read as a valid ID. 
[moov] size=8+138376

```` 

Scary, it is almost if there are 2 parallel structures. In that dashed tag, there was another tag I could jump in as I did in the fix.

Thank you for this challenge, I enjoyed it.

**Comment by Borewit** [comment]
Fixed in [v3.1.2](https://github.com/Borewit/music-metadata/releases/tag/v3.1.2), enjoy.

**Comment by LudekStoklasa** [comment]
Thanks so much for a quick fix!
I can confirm it is working now! ;-)

**Comment by Borewit** [comment]
Unknown atoms are ignored.
Problems was that the atom header was considered to be invalid. More specific the [FourCC](https://en.wikipedia.org/wiki/FourCC) identifier. Ofcourse I can accept any binary value, but of the identifier contains garbage, it is an indication I am reading something which is not the FourCC, at the parser is completely out-of-sync. At this point, all of the following atoms cannot be read neither.
I am not sure the FourCC atom identifiers in your sample are valid, but they are tolerated by music-metadata after the fix.
