### ISSUE TITLE
multiple album-artists fails

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#1649]
@Borewit I tagged some files using Picard, and I can't seem to get multiple album-artists. I tried ID3v2.4, and ID3v2.3 with "/", "; ", and " / " separators. With ID3v2.4, the `results.native` value does show multiple "TPE2"  header values. But music-metadata only uses the last one.

_Originally posted by @binyamin in https://github.com/Borewit/music-metadata/issues/432#issuecomment-1518358520_

**Comment by Borewit** [comment]
@binyamin, the `common.albumartist` is the literal written album artist e.g.: `"Beth Hart & Joe Bonamassa"`

I thought this was in line with the way Picard encoded the metadata. If you believe it is done different, let me know and please provide a sample.

**Comment by binyamin** [comment]
Sorry, I can upload a file shortly. If you would reopen the issue, please.

**Comment by binyamin** [comment]
Here's the sample file: https://www.dropbox.com/s/iz0q4yotq0j0bv9/issue-1649.mp3?dl=0

I put the same 2 artists for "albumartist" and "artists".

Here's what I got from music-metadata:
```jsonc
// result.common
{
  track: { no: null, of: null },
  disk: { no: null, of: null },
  movementIndex: {},
  title: 'issue-1649',
  encodersettings: 'Lavf60.3.100',
  albumartist: 'Jane Smith',
  artist: 'John Doe & Jane Smith',
  artists: [ 'John Doe', 'Jane Smith' ]
}
```

**Comment by Borewit** [comment]
I see what you mean @binyamin.

But according to the Picard convention, you used `albumartist` different.
It designed to be 'John Doe & Jane Smith' and not `[ 'John Doe', 'Jane Smith' ]`

This is how Picard defined it's tag mapping: https://picard-documentation.readthedocs.io/en/latest/appendices/tag_mapping.html

As you can see there is a distinction between artist (singular) & artists (plural):

```js 
artist: 'John Doe & Jane Smith',
artists: [ 'John Doe', 'Jane Smith' ]
```
for the album artist, there is no plural defined (there is no album artist**s**).

Therefor I implemented the album artist**s** in common as singular:

https://github.com/Borewit/music-metadata/blob/860bc39c93ed2accb0b54e2c91e4f71d223e7be1/lib/common/GenericTagTypes.ts#L147

Of-course I could also make every singular field an array, so in case the are defined multiple times, you can access each of them. But that means it becomes harder to access those fields for users who expect them to be used in the conventional way.

What I could possible do, is  converting `[ 'John Doe', 'Jane Smith' ]` to ` John Doe & 'Jane Smith`, and maybe generate a warning.

**Comment by binyamin** [comment]
@Borewit I see the issue here.

Note that I actually _used_ Picard to tag this file. Under `tags > id3`, setting the version to `v2.3` will concatenate multiple album artists by a given specifier. However, when set to `v2.4`, it will write them as separate entries. I tried to check the ID3 website for further details, but it gives me a 500 error.

Honestly, I don't understand why Picard only decided to make "artist" plural, but not "album artists".

**Comment by Borewit** [comment]
Hi @binyamin,

I cannot reproduce the presence of plural album-artists field using version 2.4 ID3 tag in Picard as you described.

I have an [ID3v2.4 track in the unit tests](https://github.com/Borewit/music-metadata/blob/860bc39c93ed2accb0b54e2c91e4f71d223e7be1/test/samples/MusicBrainz%20-%20Beth%20Hart%20-%20Sinner's%20Prayer%20%5Bid3v2.4%5D.V2.mp3), which has 2 individual album artists.

First track of [this MusicBrain album](https://musicbrainz.org/release/e7050302-74e6-42e4-aba0-09efd5d431d8), with album-artists defined:
1. [Beth Hart](https://musicbrainz.org/artist/3fe817fc-966e-4ece-b00a-76be43e7e73c)
2. [Joe Bonamassa](https://musicbrainz.org/artist/984f8239-8fe1-4683-9c54-10ffb14439e9)

As you can see, the album-artist as combined as a single value, while it is pointing multiple MBID's (`MUSICBRAINZ_ALBUMARTISTID`).
I thought maybe they updated the behavior of Picard, so I updated to version 2.8.2. I cleared all metadata from that track, set Picard to use ID3v2.4 and re-wrote the metadata, yet the behavior is my opinion that it is still combining the artists in a single field. 

![image](https://github.com/Borewit/music-metadata/assets/23255260/593d2596-c139-4550-a07b-6c1228f1686f)

**Comment by Borewit** [comment]
I thought I updated to latest version of Picard, but I forgot to run the installer. :see_no_evil:

With Picard 2.8.5 same behaviour:

![image](https://github.com/Borewit/music-metadata/assets/23255260/f2fd0118-3e18-4841-a11e-33ef9950bca6)

**Comment by binyamin** [comment]
This is so odd. I downloaded your file, and was able to write it as separate fields. Maybe you need to re-set the config after updating?

What are your system specs? I'm using Picard v2.8.5, installed via flatpak, on Manjaro Linux 22.1.

**Comment by Borewit** [comment]
Picard v2.8.5 installed om Windows 10.

**Comment by Borewit** [comment]
I see that for some magic reason we have different results. My results are in line with the documentations, so I see no way how to this any different. Hence I close the issue. Feel free to reopen, if you find some solid eveidence that `albmumartists` became a plurar concent.

**Comment by ma225tq** [comment]
Hey @Borewit,

Jumping in here, is there any reason you don't want to support multiple frames / null-separated multiple values for albumartist (regardless of Picard)?

The library already handles this for artist → artists in MetadataCollector.ts:159-170. Multiple TPE1 frames get collected into common.artists. Null-separation is handled in ID3v2Parser.ts:132 where arrays from splitValue() trigger multiple addTag() calls.

But the same logic doesn't exist for albumartist. Multiple TPE2 frames or null-separated values just get overwritten, losing all but one.

E.g.
```
TPE1: ["FirstArtist", "SecondArtist"]  →  common.artists: ["FirstArtist", "SecondArtist"] ✓
TPE2: ["FirstArtist", "SecondArtist"]  →  common.albumartist: "FirstArtist" ✗
```

Bumped into this when using kid3 for tagging. 

Since you already handle both cases for artist (null-separated and multiple frames), is there a reason not to do the same for albumartist? 

This would require very minor code changes, I'd be happy to open a PR.

**Comment by Borewit** [comment]
@ma225tq, that does sound reasonable.
