### ISSUE TITLE
APEv1/2 Replaygain Tags

### ISSUE THREAD

**Issue by gr0ebi** [Borewit/music-metadata#191]
**Feature Request**
Will it be possible to view APEv1/2 Replaygain Tags?
Common Metadata in the docs saying that you can't view them at the moment

**Comment by Borewit** [comment]
You can access them as native tags.

I will add them to common as well, is some work, requires normalization of value (some are in dB, some are a ratio), give me a few days.

**Comment by gr0ebi** [comment]
> You can access them as native tags

Didn't know that, thx a lot for your fast answer

**Comment by gr0ebi** [comment]
I just tried a test mp3 that I has a replaygain APE tag, but the tag didn'show up
Am I doing something wrong? Same output with and without replaygain

> meta.parseFile('/home/nodejs/test.mp3', {native: true, skipCovers: true})
    .then( metadata => {
        console.log(util.inspect(metadata, { showHidden: true, depth: null, skipCovers: true}));
    })
    .catch( err => {
        console.error(err.message);
    });

**Comment by Borewit** [comment]
An MP3 with an APE tag, that sounds like an odd combination. 
Can you zip and drop the file here?

**Comment by gr0ebi** [comment]
[test.zip](https://github.com/Borewit/music-metadata/files/2841498/test.zip)
Tag was created with mp3gain version 1.6.2
help is showing "use APE tag for MP3 gain info (default)" thats why I thought it's the way to go

**Comment by Borewit** [comment]
That file is indeed extended with an APE header, with the replay tags. This is pretty non standard, and therefor not a lot (probably close to none) software will support it.

In addition to that, I think ID3, the defacto-standard metadata-header MP3, [has support for replay-gain-adjustments](http://id3.org/Replay%20Gain%20Adjustment).
Note that the replay tags in the APE headers, are probably more based on convention rather then they are explictly identified by the APE standard.

Despite the APE header is non standard, I am in principle open to support this in music-metadata as well, however the problem is with APE headers that they appear at the end of the file. In combination with MPEG, which does not give me any indication where the start of the header is, without parsing each and every frame, this gives will give a lot of overhead.

**Comment by gr0ebi** [comment]
ok thanks a lot, I will use ID3 tags then!
this can ble closed then
