### ISSUE TITLE
parseStream on s3 stream not working - no errors, but execution halts

### ISSUE THREAD

**Issue by ffxsam** [Borewit/music-metadata#256]
**Bug description**
For some reason, `mm.parseStream` fails to work. My code doesn't throw any exceptions, but the execution halts at that point.

**Expected behavior**
I expected `parseStream` to work properly.

```js
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3();
const mm = require('music-metadata');

(async function() {
  const stream = s3
    .getObject({
      Bucket: 'my-bucket',
      Key: 'test.wav',
    })
    .createReadStream();

  const data = await mm.parseStream(stream);
  console.log('we never get here :(', data);
})();
```

**Comment by Borewit** [comment]
Can it be that  `.createReadStream()` returns a [browser stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)?

`mm.parseStream(stream)` expects a [node.js stream](https://nodejs.org/api/stream.html).

If this is the case, you have few options:
- Use [parseReadableStream of music-metadata-browser](https://github.com/Borewit/music-metadata-browser#parsenodestream-function)
- Convert the stream using: [readable-web-to-node-stream](https://github.com/Borewit/readable-web-to-node-stream)

**Comment by Borewit** [comment]
Ignore previous suggestion, you get a [node.js stream](https://nodejs.org/api/stream.html) out of the box.

**Comment by Borewit** [comment]
What if you run?
```js
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3();
const mm = require('music-metadata');

(async () => {
  const stream = s3
    .getObject({
      Bucket: 'my-bucket',
      Key: 'test.wav',
    })
    .createReadStream();

  console.log('Parsing...');
  try {
    const data = await mm.parseStream(stream);
    console.log('we never get here :(', data);
  } catch(e) {
    console.error(`Oops: ${e.message}`);
  }
})();
```

**Comment by Borewit** [comment]
@ffxsam: is this still an issue?

**Comment by ffxsam** [comment]
Hey, I'm on a trip but will give it a try when I get back. But no errors are being thrown so I don't think this will make a difference.

**Comment by Borewit** [comment]
```js
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3();
const mm = require('music-metadata');

(async () => {
  const stream = s3
    .getObject({
      Bucket: 'music-metadata',
      Key: 'Various Artists - 2008 - netBloc Vol 13 (color in a world of monochrome) {BSCOMP0013} [MP3-V0]/01 - Nils Hoffmann - Sweet Man Like Me.mp3',
    })
    .createReadStream();

  console.log('Parsing...');
  try {
    const data = await mm.parseStream(stream);
    console.log('metadata:', data);
  } catch(e) {
    console.error(`Oops: ${e.message}`);
  }
})();
```

output:
```js
Parsing...
metadata: { format:
   { tagTypes: [ 'ID3v2.4' ],
     lossless: false,
     container: 'MPEG',
     codec: 'MP3',
     sampleRate: 44100,
     numberOfChannels: 2,
     bitrate: 160000,
     tool: 'LAME3.100',
     duration: 274.99102040816325,
     codecProfile: 'V0' },
  native: undefined,
  quality: { warnings: [] },
  common:
   { track: { no: 1, of: 10 },
     disk: { no: 1, of: 1 },
     title: 'Sweet Man Like Me',
     artists: [ 'Nils Hoffmann' ],
     artist: 'Nils Hoffmann',
     album: 'netBloc, Volume 13: Color in a World of Monochrome',
     year: 2008,
     date: '2008-02',
     genre: [ 'Pop Rock' ],
     compilation: '1',
     originaldate: '2008-02',
     label: [ 'blocSonic' ],
     script: 'Latn',
     media: 'Digital Media',
     artistsort: 'Hoffmann, Nils',
     albumartist: 'Various Artists',
     albumartistsort: 'Various Artists',
     originalyear: 2008,
     catalognumber: [ 'BSCOMP0013' ],
     releasestatus: 'official',
     releasecountry: 'XW',
     releasetype: [ 'album', 'compilation' ],
     acoustid_id: '929b4f06-2ba3-4457-a335-2c1857ecccef',
     license: 'https://creativecommons.org/licenses/by-nc-nd/3.0/\u0000',
     musicbrainz_albumid: 'abf39f57-0b01-4b51-9c1e-b21e8ada5091',
     musicbrainz_recordingid: '751dbbf7-f4b6-4c10-92bd-70990c99039d',
     musicbrainz_artistid: [ '6b359560-c448-44c0-84d0-d540f474d32e' ],
     musicbrainz_albumartistid: [ '89ad4ac3-39f7-470e-963a-56509c546377' ],
     musicbrainz_releasegroupid: 'cfd81e60-9528-31a3-8c73-4843409ee8a1',
     musicbrainz_trackid: 'b6f2b632-e267-3497-9071-97cafc1a3b35',
     picture: [ [Object] ] } }

```
worked for me Sam.

**Comment by Borewit** [comment]
@ffxsam is the issue resolved?

**Comment by ffxsam** [comment]
@Borewit Hey, sorry about that! Let me put together a reproduction for you, one that you can just easily deploy to AWS (and remove cleanly). Please leave this issue open and I'll try to get to it this week.

BTW, my workaround is this:

```ts
  try {
    const s3obj = new S3Object({ bucket: event.bucket, key: event.key });
    const body = await s3obj.getBody();
    // @ts-ignore
    const metadata = await mm.parseBuffer(body);

    // Just remove cover images for now
    delete metadata.common.picture;

    return {
      success: true,
      metadata,
    };
  } catch (e) {
    console.log(
      JSON.stringify({
        error: true,
        reqId: event.reqId,
        reason: e.message,
      }),
    );
    return { success: false };
  }
```

Is there any disadvantage to reading the whole file like this, besides consuming memory? Will `mm.parseStream` just read enough to get the metadata and not read the whole file?

**Comment by Borewit** [comment]
You can use the _skipCovers_ option to prevent those from being returned and loaded in the first place.
```js
const metadata = await mm.parseBuffer(body, {skipCovers: true});
```

**Comment by ffxsam** [comment]
Great, thanks! And it looks like `duration: false` (the default) will make `parseStream` not have to stream in the entire file, correct?

**Comment by Borewit** [comment]
Indeed, if the duration flag is set, it will not parse the entire file if that is what it takes to extract the duration. If the duration if obvious (can be extracted from a header), it will neither parse the entire file.

**Comment by ffxsam** [comment]
Got it! I can even replicate it in just basic Node.js (without Lambda).

It's a file size issue. With a 1MB WAV file, it works perfectly. On a 31MB WAV file, it fails silently. Any ideas why it might do this?

**Comment by ffxsam** [comment]
Actually, I'm just making an assumption that file size is the problem. I guarantee the WAV files I'm testing on are valid, but maybe there's something about their format that's causing an issue.

**Comment by ffxsam** [comment]
Did a bunch of different tests. It works on files until they're about 50 seconds long (8.8MB). If they're shorter, no problem. Very odd. Let me know if you need a WAV file from me.

**Comment by Borewit** [comment]
I have been able to reproduce the issue.

The duration flag is no effect on the WAV-parser, the WAV-parser will read the entire stream. Internally it will ignore the data chunk, which means reading for stream which is really expensive. Reading a file is efficient, just the stream which is currently in-efficient.

The only way to mover further in a stream is by reading it. This tried in one go, which causes node to quit silently. That is the reason it it size related. This is the first think I will fix. After that I will try to make the WAV stream reading more efficient.

**Comment by Borewit** [comment]
Caused by Borewit/strtok3#55

**Comment by Borewit** [comment]
Should be solved, sorry I cannot easily prevent reading the entire WAV via a stream is not something I can prevent here; see #283.

**Comment by ffxsam** [comment]
@Borewit Works like a charm, thank you!!

**Comment by Borewit** [comment]
Thanks so much @ffxsam!

If performance to the S3 storage becomes an issue, I can investigate if it is suitable for a chunk based client.

**Comment by ffxsam** [comment]
@Borewit All of this interaction is Node.js only. My use case:

When a user drops a new WAV file into my AWS S3 bucket, a series of AWS Lambda functions get executed to process it (transcode, generate image waveforms, etc). One of those things is grabbing metadata from the file and storing it in a database. I figured `mm.parseStream` was a better bet than `mm.parseBuffer` so I didn't have to read the entire file into memory.

I don't expect any performance issues though, so far it's seemed pretty snappy! The only other bonus would be if `parseStream` could just return as soon as it has all the tag data. I don't know WAV file format or how/where metadata is stored, but is it possible for `parseStream` to just return as soon as it has reached & parsed the metadata chunk? Or is it possible some of that data could be at both the beginning and end of the file?

Not a huge deal, since it does seem pretty fast. Just to clarify how this works: I'm assuming `parseStream` only reads in so many bytes at a time, and doesn't keep a running buffer, correct?

**Comment by Borewit** [comment]
> The only other bonus would be if `parseStream` could just return as soon as it has all the tag data.

That is what I tried in #283, but it does not make any difference since the EXIF metadata is stored **after** the audio data chunk. So it has to read all the way to end of the stream, until the end of the file is almost reached, to be able to read the metadata.

The only alternative is to jump forward in a file. This is not possible via a stream, but it is possible to request chunks of data via HTTP requests, if and only if both the client and server supports it. 

It would allow to do something like:
```js

// mmCore grants access some lower level music-metadata functions
const mmCore = require('music-metadata/core');

// This represents a WAF file dropped by a user
const s3obj = new S3Object({ bucket: event.bucket, key: event.key });

// This is an imaginary class which supports chunked based reading from S3 object
// this implements the ITokenizer interface, which can be converted to more specific reads
const someS3orHttpRangedReader = new SomeS3orHttpRangedReader(s3obj);

const metadata = mmCore.parseFromTokenizer(someS3orHttpRangedReader);
```

For sure S3 supports a [proprietary way of chunked reading](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax).

**Comment by ffxsam** [comment]
I see, so the EXIF data is _always_ after the audio chunk. Makes sense.

I do know that `S3.getObject` will let you grab a byte range, but I'm not sure how I would know what range to grab, exactly. Unless the EXIF data is always in the last `X` bytes of the file. Not to mention, I actually can't guarantee the uploaded file will be WAV. It could also be MP3.

**Comment by Borewit** [comment]
> but I'm not sure how I would know what range to grab

But music-metadata knows. Via the ITokenizer the _SomeS3orHttpRangedReader_ can calculate this. I am considering to implement something like that, because I already have done it for the browser.

> But again, it's not a huge deal. Using Node.js's streams should be sufficient!

Understood. Don't worry, this is an area which has my interest.
In addition to that, I see a growing number of users reading directly from cloud storage.

**Comment by ffxsam** [comment]
Cool, I appreciate your help. I understand this is open source so I never want to make demands, of course. 😁But I'm happy to make donations for help, too.

**Comment by Borewit** [comment]
Using an experimental version of [music-metadata](https://github.com/Borewit/music-metadata) and 
[streaming-http-token-reader](https://github.com/Borewit/streaming-http-token-reader) reading a WAVE-file of ~53 MB stored on S3 cloud:

```js

//
// Example chunked streaming audio track from S3 buckets into music-metadata parser
//

const S3 = require('aws-sdk/clients/s3');
const s3 = new S3();
const mm = require('music-metadata');
const {StreamingHttpTokenReader} = require('streaming-http-token-reader');
const {parseContentRange} = require('streaming-http-token-reader/lib/http-client');

const wav = 'WAV/02 - Poxfil - Solid Ground.wav';

const config = {
  avoidHeadRequests: true
};

class S3Request {

  constructor(bucket, key) {
    this.bucket = bucket;
    this.key = key;
  }

  async getResponse(method, range) {

    return s3.getObject({
      Bucket: this.bucket,
      Key: this.key,
      Range: `bytes=${range[0]}-${range[1]}`
    }).promise().then(data => {
      return {
        contentLength: data.ContentLength,
        contentType: data.ContentType,
        contentRange: parseContentRange(data.ContentRange),
        arrayBuffer: async() => {
          return data.Body
        }
      }
    });
  }
}

(async () => {

  const s3Request = new S3Request('music-metadata', wav);

  console.log('Parsing...');
  try {
    const streamingHttpTokenReader = new StreamingHttpTokenReader(s3Request, config);
    const t0 = new Date().getTime();
    await streamingHttpTokenReader.init();
    const metadata = await mm.parseFromTokenizer(streamingHttpTokenReader, streamingHttpTokenReader.contentType, {});
    const t1 = new Date().getTime();
    console.log(`Read metadata in ${t1 - t0} milliseconds.`);
    console.log('metadata:', metadata);
  } catch (e) {
    console.error(`Oops: ${e.message}`);
  }
})();
```
Outputs:
```
Read metadata in 479 milliseconds.
metadata: { format:
   { tagTypes: [ 'exif', 'ID3v2.3' ],
     container: 'WAVE',
     codec: 'PCM',
     bitsPerSample: 16,
     sampleRate: 44100,
     numberOfChannels: 2,
     bitrate: 352800,
     lossless: true,
     numberOfSamples: 13407768,
     duration: 304.0310204081633 },
  native: undefined,
  quality: { warnings: [] },
  common:
   { track: { no: 2, of: 10 },
     disk: { no: 1, of: 1 },
     album: 'netBloc, Volume 13: Color in a World of Monochrome',
     artists: [ 'Poxfil' ],
     artist: 'Poxfil',
     genre: [ 'Netlabel' ],
     title: 'Solid Ground',
     year: 2008,
     date: '2008',
     albumartist: 'Various Artists',
     acoustid_id: '48370888-616a-4b28-808d-9e49d41c8bce',
     catalognumber: [ 'BSCOMP0013' ],
     originalyear: 2008,
     releasecountry: 'XW',
     script: 'Latn',
     picture: [ [Object] ] } }
```

**Comment by Borewit** [comment]
As an S3 could storage user, you may be interested in this topic as well @kimfucious.

**Comment by ffxsam** [comment]
@Borewit I missed this bit you said earlier:

>Internally it will ignore the data chunk, which means reading for stream which is really expensive. Reading a file is efficient, just the stream which is currently in-efficient.

So as of right now, I should be using `mm.parseBuffer` instead of `parseStream', but this new `parseFromTokenizer` combined with `StreamingHttpTokenReader` would allow highly efficient grabbing metadata from WAV & MP3 files?

**Comment by Borewit** [comment]
#### Stable and proven technology
`mm.parseStream` is better then  `mm.parseBuffer`
- a little faster (parsing while reading)
- no huge memory spike
- you will not run into max file size issues

`mm.parseFile` is performs better (in some cases) then  `mm.parseStream`, **but** it requires direct file access. It is not an option for you in this scenario. But the reason it is faster is interesting. It because file has random access.  I can read at any offset data. This is an advantage for files which require part of the data to be read at the beginning of the file, and part of it at the far end. For stream compliance the internal parsers of music-metadata always read the audio sequential. They start reading at the beginning, and they quit when they 100% sure they got all metadata. To make parsing of those nasty files, which have metadata all the way at the end, using `mm.parseFile` faster it is using two different read methods:
- read, which reads from the "stream"
- ignore, in case of a file it will only move the offset pointer forwards, it will not actually read
In case of a real stream, read and ignore are both mapped to actual read operation.

This bug was by the way caused in the ignore-read on a stream, trying to read the entire WAV-chunk at once. Apparently node.js does not like that, which I think is a bug node.js.

#### Experimental

The way files are accessed we can also map to HTTP chunked reads use byte-range requests. However HTTP does not have the same characteristics as file access. The access time (the overhead of each read transaction) is way higher. So we don't want read byte for byte. That is basically what [streaming-http-token-reader](https://github.com/Borewit/streaming-http-token-reader) does, it converts the read and ignore operations to multiple HTTP chunked read operations. It also combines smaller read operation into a combined read operation. As far as I know, only used by 1 user (@icidasset).

[streaming-http-token-reader](https://github.com/Borewit/streaming-http-token-reader) is designed to run in the browser, surprisingly I could quite easily make it work in node.js as well. 

But at this point it would only work on public HTTP environment. With public I mean, no authentication requirements like on the S3 cloud.

I considered 2 ways to get it working on the private S3-file-storage:
- Pass the authentication headers to [streaming-http-token-reader](https://github.com/Borewit/streaming-http-token-reader)
- Let the 'aws-sdk/clients/s3` do with trick HTTP requests

I picked the second option, invested some more time to be able to hookup an external HTTP-client, and wired it to S3-client as done in [comment above](https://github.com/Borewit/music-metadata/issues/256#issuecomment-544183155)

_When do you benefit from chunked-reading?_
Entirely dependents on the file type, typically larger audio files which have or may have audio at the end, like:
- WAVE
- m4a

Not a lot or limited advantage reading:
- FLAC
- MP3

**Comment by icidasset** [comment]
> But at this point it would only work on public HTTP environment. With public I mean, no authentication requirements like on the S3 cloud.

I'm using music-metadata with [presigned S3 urls](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html).
So this works for private buckets as well.

The only difficult bit was that HTTP method is encoded into the url, so the url for a `HEAD` request would different than the url for a `GET` request. I had to trick music-metadata into using two different urls. The code for that is on Github if you want to take a look: https://github.com/icidasset/diffuse/blob/master/src/Javascript/processing.js

**Comment by Borewit** [comment]
Thanks for you reply @icidasset!

>I'm using music-metadata with presigned S3 urls. So this works for private buckets as well.

Interesting, so that would make the code even simpler. Can we get a *presigned S3 url* for any given *bucket*-*key*-pair?

> The only difficult bit was that HTTP method is encoded into the url, so the url for a HEAD request

Alternatively you may go around the HEAD-request using: 
```js
const config = {
  avoidHeadRequests: true
};
```
see [example above](https://github.com/Borewit/music-metadata/issues/256#issuecomment-544183155)

This will use a GET / range request with a 0-byte range instead.

Off-topic @icidasset: I want to ask you a favor. Can you please do an attempt to integrate [diffuse-musicmetadata](https://github.com/icidasset/diffuse-musicmetadata) directly into [diffuse](https://github.com/icidasset/diffuse)? The reason I am asking, after a long journey how I could make music-metadata suitable and easy usable the in browser usage, I now strongly believe it works best in combination with a module bundler. It looks like that nowadays, it can be easily included with Angular, React, webpack and probably others, without complex tweaking. I think [diffuse](https://github.com/icidasset/diffuse) deserves to be in the list of [Audio Tag Analyzer, Webamp, audioMotion](https://github.com/Borewit/music-metadata-browser#online-demos), but I don't want to encourage anyone to use (and copy) the minified output [diffuse-musicmetadata](https://github.com/icidasset/diffuse-musicmetadata). I am worried this will result in dependency conflicts, loss of configuration management, old versions popping up in the wild and missed opportunities for me to receive feedback on properly integrated projects. So as long you don't check-in the module-bundlers output, I am happy.

**Comment by icidasset** [comment]
> Can we get a presigned S3 url for any given bucket-key-pair?

Yeah.

Here's how I do it: https://github.com/icidasset/diffuse/blob/3b83b38f23e9cfde1b61b7039a56e9d7b225ab7c/src/Library/Sources/Services/AmazonS3/Presign.elm
It's written in Elm, but it should explain the process nonetheless.

> Alternatively you may go around the HEAD-request using ...

Cool, thanks! No downsides to doing this?

---

Regarding off-topic, I'll message you on Discord.
