### ISSUE TITLE
Fields calculated wrong for APEv2 Tags

### ISSUE THREAD

**Issue by vladotesanovic** [Borewit/music-metadata#331]
**Bug description**
Number of APE tags are not calculated right. There is 11 tags, while peekToken function returns 12

![tags](https://user-images.githubusercontent.com/738638/69134106-4cae3680-0ab7-11ea-90e6-25596de63919.png)

Above ALBUM tag is number of fields function returns.

**Expected behavior**
Function should return 11 instead of 12

**Audio file demonstrating the problem**
Audio file can be found here: https://we.tl/t-RSvWv2s177

I reproduced this with simple unit test:

```
    it('should be able to parse APEv2', async () => {

        const filePath = path.join(samplePath, 'mp3', 'crim2.mp3');

        const metadata = await mm.parseFile(filePath);
    });
```

**Comment by Borewit** [comment]
I examined the file, and I have been able to reproduce the issue. 
I believe the APE header is indeed a little bit corrupt.
Just 1 single bit. 

The issue is in the [APE footer](https://wiki.hydrogenaud.io/index.php?title=APE_Tags_Header) in the field holding the _Number of items in the Tag (n)_.

_Note that the friendly people of Monkey-audio call what I call a header a tag, and the tag an item._

The header lists the number of items.
Your APE footer has the _item count_ set to 11:
`0000 0000 0000 0000 0000 0000 0000 101`**1**

However there are only 10 _items_:
`0000 0000 0000 0000 0000 0000 0000 101`**0**

This will cause the current APEv2 parser to reader 1 `tag-item-header` to many, when the end of the buffer has been reached.

https://github.com/Borewit/music-metadata/blob/5602e57dcdb37e1ac1bc6b78c9c776edaa9c4767/lib/apev2/APEv2Parser.ts#L100-L102

After tag (item) #10, the `offset === buffer,length`.

**Comment by Borewit** [comment]
Script to trim sample file:
```bash
#!/bin/sh

IN=crim2.mp3

APEv2OFFSET=14132877

MPEGOFFSET=194984

MPEGFRAME3=197072

#dd count=$MPEGOFFSET bs=1 "if=$IN" of=header.id3v2
dd count=$MPEGFRAME3 bs=1 "if=$IN" of=3frames.mp3
dd skip=$APEv2OFFSET bs=1 "if=$IN" of=header.apev2

cat 3frames.mp3 header.apev2 > issue-331.mp3
```

**Comment by Borewit** [comment]
I just noticed I did not read your analysis good, yeah you nailed it as well, wrong item count.

But I think the issue is in the source format as you suggested elsewhere.

**Comment by Borewit** [comment]
Should no longer be fatal in version [v5.0.1](https://github.com/Borewit/music-metadata/releases/tag/v5.0.1).

**Comment by vladotesanovic** [comment]
@Borewit Yes, thank you. My solution was different but similar to yours. 

Thanks again

**Comment by Borewit** [comment]
Oh you already had solution in the pipeline, my fault, sorry about that.

Thank you for making music-metadata a better module.
