### ISSUE TITLE
Incorrect metadata retrieval again

### ISSUE THREAD

**Issue by mycoboco** [Borewit/music-metadata#42]
After I had learned that some of my mp3's had multiple headers, I reset them to make every kind of headers (IDv1, IDv2 and so on) have the same tag values, but `music-metadata` still keeps failing to get correct metadata from some of them. I double-checked the files in question had headers properly set with at least two metadata editors.

I attach two samples to help you figure out the cause.

[sample1.mp3.zip](https://github.com/Borewit/music-metadata/files/1305328/sample1.mp3.zip)
[sample2.mp3.zip](https://github.com/Borewit/music-metadata/files/1305330/sample2.mp3.zip)

**Comment by mycoboco** [comment]
Probably these attached files also have multiple instances for the same tag type (e.g., two headers for IDv2.4), and as you explained in #40, `music-metadata` reads the last found one. But many tag editors seem to read the first one, I guess, when there are multiple candidates, which means there is no easy way for users to edit tag values for `music-metadata`.

**Comment by Borewit** [comment]
Both of these files contain 2 ID3v2.4 headers. This utility shows [MPEG-Audio-Frame-Header](https://www.codeproject.com/Articles/8295/MPEG-Audio-Frame-Header) shows presence of multiple headers:
![multiple headers](https://user-images.githubusercontent.com/23255260/30495972-5547da52-9a4e-11e7-91c7-ec4b6cfeb115.png)
Also notice the APEv2 header :-1:.

I think you are right, it is arbitrary how most software handles these multiple tag blocks. I will take it into consideration to make all of the ID3 tag headers accessible (via _native_ tags) which does not solve your problem. I could pick the the first ID3 header instead of the last one.

Approaching the problem form a different angle, how can you fix your files?

My favorite music metadata tool is [Picard](https://picard.musicbrainz.org/downloads/) which also runs on OS-X. [Picard](https://picard.musicbrainz.org/downloads/) basically uses (MusicBrainz)[https://musicbrainz.org/] to lookup metadata. Although I failed to lookup these 2 tracks, I still use it to fix the problem by select the track in the _Unmatched Files_ list, hit the _Save_ button, and only a single ID3v2.4 tags was left over. 
Note that the result is depending of what you have selected at the options menu, you can chose to strip APEv2 from FLAC and choose whether you prefer ID3v2.3 or ID3v2.4.

**Comment by mycoboco** [comment]
Thanks for the reply and the analysis of my files.

Yes, different tools for tagging audio files seem to behave in different ways when reading metadata from multiple headers; simply choosing the first one, making a new one by merge and so on. I had suspected `mp3-metadata` could not properly retrieve metadata from some files until I found a small tool to remove existing headers which reveals existence of the last header set to the incorrect values `mp3-metadata` showed.

The only way for me to fix my files is to use the tag remover and set metadata properly again, which is surely cumbersome considering that the files already have proper metadata set in their first headers.

Thanks for letting me know the nice tool. Unfortunately, it also often fails to remove existing headers when manually editing tag values; only getting rid of all existing headers and setting to new values work. I think many users have no idea mp3's can have multiple headers and one can hides others. Furthermore, tagging tools that show the first header are likely to overwrite only the first one leaving others untouched.

**Comment by Borewit** [comment]
If you know how to write Python you can use [Mutagen](https://github.com/quodlibet/mutagen) to apply the fixes. It is not rocket science to remove duplicate headers and for instance keep the first one.

We can also tweak music-metadata on a branch to do the trick. If we expand the _native_ metadata response a bit, so that all headers found are registered. Secondly we need to register the offset and the length of each ID3 blocks. Once we have that, we can identify header collisions and can fix them by rewriting the files with the blocks we want to keep.

**Comment by mycoboco** [comment]
I can write simple Python code so can take advantage of Mutagen to fix my problematic files in a batch. Thank you for informing of the library. Or Even if I would do it manually, never a burden because they are not many.

I think it is not necessary to make `music-metadata` support fix of multiple headers, but what I wonder is if the change made between `0.8.2` and `0.8.3` to pick the last header when there are multiple ones is really necessary; as I recall `0.8.2` worked well. Or at least documentation seems to be worth being added to explain `music-metadata` chooses the last of multiple headers; as I did, users might mistake that `music-metadata` is broken because it looks like giving incorrect values even after they fix tag values using tagging tools.

**Comment by Borewit** [comment]
Since [0.8.3](https://github.com/Borewit/music-metadata/releases/tag/v0.8.3)  multiple ID3 headers are supported, and the "best" header is selected. In case two header block appear of the same version and format (which should not ever happen parsing a properly encoded MP3 file), the last one will overwrite the previous one in the result. I should [improve the documentation](#17), problem is that I prefer coding, and there is always something more to add.
