### ISSUE TITLE
Encoding windows-1250   

### ISSUE THREAD

**Issue by pykaso** [Borewit/music-metadata#44]
Hi, We are processing MP3 files from our supplier and some ID3 strings are saved in exotic encoding. I guess windows-1250.  In this case, strings with accented chars are read corrupted.

**Comment by Borewit** [comment]
Exotic characters should not be a problem, encoding should be in line with the ID3 specification.
If you send me a sample (borewit@xs4all.nl) I can have a look .

If applicable. let me know what I can use as public test data. I usually keep the header & ~2 seconds of the audio data.

**Comment by pykaso** [comment]
I don't know how to safely cut mp3 without loosing id3 tags, so here is one in full length: 
https://1drv.ms/f/s!Amk9XhZSKB38pOUKmjBHe1jbOiP3XQ
I Am not the author, so I can't allow to use it public.  
Thx

**Comment by Borewit** [comment]
The MP3 file you gave me for analysis has 2 ID3 headers:
   - ID3v2.3
   - IDv1.1

To me the ID3v2.3 header looks fine, decoding the album name `Zbožòuju tvou buchtu`  as it should be I suppose. This is mapped to common, so you should see all the generic tags correctly I guess....
      
The ID3v1.1 header is supposed to be ISO 8859-1; ref: https://nl.wikipedia.org/wiki/ID3_(tag)

The `ž` is not part of that (encoded as 0x9E).
I think the album title is encoded with ANSI (Windows-1252), which is small extension to 
 ISO 8859-1: https://nl.wikipedia.org/wiki/ANSI-tekenset. Note the difference marked in yellow.

So the ID3v1.1 as provided is not really maybe not 100%, but in my opinion acceptable.
I will update music-metadata so that ID3v1.1 is decoded using Windows-1252 instead of ISO 8859-1.

Does that solve your problem?

**Comment by pykaso** [comment]
The right album name is "Zbožňuju tvou buchtu",  (char `ň` at 5th place) so album name in ID3v2.3 is not what I expect. 

I don´t know if it's problem with music metadata. Maybe our supplier is writing incorrect ID tags.

Thanks for Your time.

**Comment by pykaso** [comment]
The Mp3tag software was read correct strings, so there must be a way to read it correctly.

**Comment by Borewit** [comment]
I missed the `ň`. I looked into the ID3v2.3 tags. The album name is stored in ID3v2.3 TALB tag (ref: [id3v2.3.0](http://id3.org/id3v2.3.0)).

The TALB tag is a Text information frame, which supports multiple types of encoding. Your supplies has chosen for type 0, which referrers to [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1).

The character ň cannot be expressed with ISO-8859-1, as simple as that.

> The Mp3tag software was read correct strings, so there must be a way to read it correctly.

Maybe it worked for you, but this what Mp3tag told me the album name was: "Zbož**ò**uju tvou buchtu"

This is the encoded album name: `5A 62 6F 9E F2 75  6A 75 20 74 76 6F 75 20  62 75 63 68 74 75`   

ň is encoded as `0xF2`. But `0xF2` is not a valid character encoding according to [ISO-8859-1](https://nl.wikipedia.org/wiki/ISO_8859-1).
[ANSI](https://en.wikipedia.org/wiki/Windows-1252) however defines `0xF2` to be the character `ò`.
Which correspons to the output I got.

It looks like indeed [Windows-1250](https://en.wikipedia.org/wiki/Windows-1250) is used.

My conclusion is that your supplier is encoding the IDv2.3 incorrect and there is no need to do so. 
ID3v2.3 allows also to use UTF-8 ot UTF-16 to encode any of these character.
I don't see a way on my side how to make decoding any better in this aspect.

I will make IDv1.1 header more flexible using ISO-8859-1, which is beyond spec, but it is known that different character set applied in this ancient header.

**Comment by pykaso** [comment]
I thought the problem would be on the supplier side.  Fortunately, We have found a workaround.
We opened all files in Mp3tag and immediately save them. This has fixed the encoding problem. 
Thanks
