### ISSUE TITLE
Very slow parsing on files that need `duration: true`

### ISSUE THREAD

**Issue by bcomnes** [Borewit/music-metadata#45]
I've come across some files that don't parse out a `duration` property.  Setting the `duration: true` option works, but it results in a very slow parse:

```
{duration: true}: 12238.523ms  # duration: true
{duration: false}: 2.982ms # duration: false
```
(example repo: https://github.com/ballpit/parsing-speed uses LFS)'

Any ideas why this file takes so long to parse out a duration property?  Are there any optimizations to this case that could be done to speed it up?

Fantastic module and work btw!

**Comment by Borewit** [comment]
Because it parses the entire file, on proper encoded MP3 file you should be able to read the duration without setting this flag.

If the MP3 file is corrupt it will take significant longer.

**Comment by bcomnes** [comment]
Do you think rewriting tags using something like taglib fix the file?

**Comment by Borewit** [comment]
I don't think that will help much. The issue probably caused by the MPEG frame holding the audio, there is probably not a good way to fix this. It requires re-encoding of the MP3 file. This requires the original source (the lossless source FLAC, WAV, ALEC, CD). [LAME](http://lame.sourceforge.net/) is the encoder to use. Re-encoding MP3 to MP3 will result in significant quality drop. Please never ever do that.

**Comment by bcomnes** [comment]
Thanks for the info, I'll play around some more to see if there are work arounds.
