### ISSUE TITLE
Can't read some songs. Empty Data

### ISSUE THREAD

**Issue by ChineseOuchie** [Borewit/music-metadata#547]
I get [empty data](https://imgur.com/XpauIxc) from a few song, but the song does have data that are viewable from other site.

In https://audio-tag-analyzer.netlify.app/ I can get all the [data](https://imgur.com/In5D092)

Code: https://github.com/ChineseOuchie/Music-Player/blob/master/server.js
Song: https://we.tl/t-34EnQX3zMR

**Comment by Borewit** [comment]
Sorry, I did not notice your issue earlier. 

Can you please make the song available one more time and update the pointer to your source code?

**Comment by ChineseOuchie** [comment]
The song: https://we.tl/t-jHJacrQxk4

Code: https://github.com/ChineseOuchie/Music-Player/blob/master/musicPlayerServer.js#L33

**Comment by Borewit** [comment]
Nothing wrong with the audio track, it parses just fine.

I think the issue is you only receive the uploaded file partially.

_Why does `NodeID3.read` work?_
It does not read as much information as [music-metadata](https://github.com/Borewit/music-metadata)

I recommend to:
*  use [`multipart/form-data`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) to upload your tracks.
* pass the content-type from the original file

To use `multipart/form-data` you need include an additional library like [multer](https://expressjs.com/en/5x/api.html#req.body).

Something like: I have **not** tested the samples below, it purely to provide some direction via code.

```js
const express = require('express');
const multer = require('multer') // v1.0.5
const mm = require('music-metadata');

const upload = multer() // for parsing multipart/form-data

app.post('/music', upload.single('audio'), (req, res, next) => {
  // req.file is the `avatar` file
  // req.body will hold the text fields, if there were any
  mm.parseBuffer(req.file.buffer, req.file.mimetype);
})
```

You also may stream the upload track into [music-metadata](https://github.com/Borewit/music-metadata):

```js
const express = require('express');
const Busboy = require('busboy');
const mm = require('music-metadata');

app.post('/music', upload.single('audio'), (req, res, next) => {
  const busboy = new Busboy({ headers: req.headers });
  const musicmetadata = await mm.parseBuffer(req.file.buffer, req.file.mimetype);
busboy.on('finish', () => {
      console.log('Upload complete');
      res.writeHead(200, { 'Connection': 'close' });
      res.end("That's all folks!");
    });
    return req.pipe(busboy);
});
```
References:
* https://gist.github.com/shobhitg/5b367f01b6daf46a0287
* https://code.tutsplus.com/tutorials/file-upload-with-multer-in-node--cms-32088

**Comment by ChineseOuchie** [comment]
I'll look into it
