### ISSUE TITLE
Description & Synopsis of AAC

### ISSUE THREAD

**Issue by chris-shaw-2011** [Borewit/music-metadata#624]
**Bug description**
If I use ffmpeg to set the metadata on an aac file like so
```
ffmpeg.exe -i "test.m4b" -map a:0 -c:a aac -metadata description="description" -metadata synopsis="synopsis" "test.out.m4b"
```
Then if I check the metadata with the following code:
```javascript
import * as mm from "music-metadata"

mm.parseFile("test.out.m4b").then(metadata => {
    console.log(metadata.common.description) //outputs ["synopsis"]
    console.log(metadata.common.synopsis) //common.synopsis doesn't exist
})
```

**Expected behavior**
```javascript
import * as mm from "music-metadata"

mm.parseFile("test.out.m4b").then(metadata => {
    console.log(metadata.common.description) //outputs ["description"]
    console.log(metadata.common.synopsis) //outputs "synopsis"
})
```
https://wiki.multimedia.cx/index.php/FFmpeg_Metadata

**Audio file demonstrating the problem**
[files.zip](https://github.com/Borewit/music-metadata/files/5234710/files.zip)

**Comment by Borewit** [comment]
Current applied mapping:

| ffmpeg      | m4a tag                 | music-metadata |
|-------------|-------------------------|----------------|
| description | desc (description)      | subtitle       |
| synopsis    | ldes (long description) | description    |

**Comment by ozelot379** [comment]
MP3Tag stores `SUBTITLE` in `desc` and `PODCASTDESC` in `ldesc` for mp4 files.
And for mp3 files it stores `SUBTITLE` in `TIT3` and `PODCASTDESC` in `TDES`.

I think, in MP3Tag `SUBTITLE` means the short description and `PODCASTDESC` the long description.

Before my PR (https://github.com/Borewit/music-metadata/pull/544), the `desc` and `ldesc` tags in mp4 files was mapped in the same field `description` and couldn't used separated, without parse the native tags self.
And for mp3 files `TIT3` was mapped to `subtitle` and `TDES` was missed.

Because you already named the short description `subtitle` for mp3, I used the same name for mp4.

But I see, it was a bad idea to name the long description `description`.

It would be ok for me, if you name the short description `description` and the long description `synopsis`, like @chris-shaw-2011 proposes, for both mp3 or mp4 files.
Alternatively, may it's also sense to name it `short_description` and` long_description`.

I can adapt my code I use music-metadata, no matter how you decide.

@Borewit I hope this can answer your questions?

**Comment by Borewit** [comment]
Thanks for your reply @ozelot379, I will follow your recommendation @ozelot379,  but I will use `description` instead of `shortDescription` for a bit more backward compatibility.          

ffmpeg      | ffmpeg  → m4a           | m4a → music-metadata |
|-------------|-------------------------|---------------------|
| description | desc (description)      | description         |
| synopsis    | ldes (long description) | longDescription    |
