### ISSUE TITLE
Is there a way to get the chapters of an audio file?

### ISSUE THREAD

**Issue by yuredev** [Borewit/music-metadata#701]
When i attach a audio file on the input, i can get several data of the file with the parseBlob method, such as: artist, album, duration, etc, but how can i get the chapters of an audio file in a .mp3 or .wma format for example?

**Comment by Borewit** [comment]
If the used chapter metadata is supported you will be able to access this via [metadata.format.chapters](https://github.com/Borewit/music-metadata/blob/41d62d796d7423f6deb624d3742d791d40a49cc6/lib/type.ts#L494).

If you find unsupported chapter formats / specification, you may create an issue for that. Please no more then 1 format per issue. I like to take small steps, otherwise I may feel lost. Please add useful corresponding documentation, provide example files, expected values / behavior, all of that is useful.

**Comment by Borewit** [comment]
You are welcome @yuredev, no problem.
