### ISSUE TITLE
Grabbing timestamp from audio file?

### ISSUE THREAD

**Issue by Cweaver136** [Borewit/music-metadata#715]
I'm hoping to grab timestamps from .voice recordings (.m4a files) I'm taking on my iPhone. I'm not seeing this as a piece of information that's returned from the library. 

I'm using parseBuffer to process my audio file and it's all working perfectly, the data just doesn't have a timestamp of when that audio recording was taken.

Not sure if this is something that's available and I'm missing or if it could potentially be added into the library?

Here's a screenshot of the data that I'm getting back:

![image](https://user-images.githubusercontent.com/38464035/103441971-dc616680-4c1f-11eb-9467-c43384f08665.png)

A great library that works as described, thanks in advance for your help.

**Comment by Borewit** [comment]
Can you provide me with a sample @Cweaver136?

**Comment by Cweaver136** [comment]
[Recording.zip](https://github.com/Borewit/music-metadata/files/5759151/Recording.zip)

Just change the file extension to be .m4a (GitHub doesn't let me upload m4a files so I had to rename it to a zip file)

**Comment by Borewit** [comment]
I don't think there are any timestamps exposed yet.

I could find the following in the file:

In the [`moov.mvhd` (Movie header atom)](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-56313) there is the:
1. creationTime = ` Sat Dec 28 2086 16:34:44 GMT+0100 (GMT+01:00)`
2. modificationTime = `Sat Dec 28 2086 16:34:51 GMT+0100 (GMT+01:00)`
(Please ignore the timezone, the value is stored in seconds since EPOCH,  so UTC).

I also found `moov.udta.date` atom, but I have not been able find any documentation.

**Comment by Cweaver136** [comment]
Okay, that's great. Would you see yourself exposing timestamps in the returned metadata object in a future pull request or update?

If not, I could fork your repo and try figuring it out myself.

Thanks for digging into this.

**Comment by Borewit** [comment]
> Would you see yourself exposing timestamps in the returned metadata object in a future pull request or update?

See PR #716.

**Comment by Cweaver136** [comment]
Wow! Thanks for your time on this project. Appreciate the responsiveness. Looking forward to using this new code.

**Comment by Borewit** [comment]
`moov.udta.date` is set to the following string: `2020-12-27T15:34:44Z`, which obviously represents a time.

I just noticed the year 2086 in the other times, I guess the `Date` conversion is really working yet.
