### ISSUE TITLE
a m4a file return error "FourCC contains invalid characters", but will play good

### ISSUE THREAD

**Issue by yimity** [Borewit/music-metadata#78]
this is the file:

[file.m4a.zip](https://github.com/Borewit/music-metadata/files/1930595/file.m4a.zip)

thank you very much.

**Comment by Borewit** [comment]
To me it looks like the file is corrupt, my best guess is a wrong atom length.
Foobar is not able to read the metadata, Mp3Tag neither.

**Comment by FranzSkuffka** [comment]
I have the same issue. Clementime and node-taglib are able to read the file. Link is here:
https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a

https://tunalib.s3.eu-central-1.amazonaws.com/cool.mp3 works.

I am parsing from a fetch read stream.

**Comment by Borewit** [comment]
The original issue repored by @yimity would throw the following error:
 `Error: FourCC contains invalid characters: 00 00 00 00`

I cannot reproduce your issue @FranzSkuffka, are you sure you are using the latest version?

Try for yourself using [audio-tag-analyzer](https://audio-tag-analyzer.netlify.com/) using music-metadata [v3.1.4](https://github.com/Borewit/music-metadata/releases/tag/v3.1.4).

Is you are still facing difficulties please create a new issue with more details.

**Comment by FranzSkuffka** [comment]
I also can not reproduce it - sorry for the confusion. However, when I fetch the file from aws and parseStream I get bad data - but only for m4a.
```js
  fetch(loc)
    .then(res => mm.parseStream(res.body, 'audio/x-m4a'))
    .then(tags => {
        console.log(tags)
        respond(JSON.stringify(tags || 'tagged'))
    })
```
output
```
[1] https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a
[1] { format: { tagTypes: [], dataformat: 'MPEG-4' },
[1]   native: undefined,
[1]   common: { track: { no: null, of: null }, disk: { no: null, of: null } } }
```

**Comment by FranzSkuffka** [comment]
I can reproduce the error by @yimity FourCC error when using the m4a mime-type on an mp3 file.

**Comment by FranzSkuffka** [comment]
With parsebuffer i get stream.copy is not a function

**Comment by Borewit** [comment]
Please post follow ups or things you want me to look in into a **new issue** @FranzSkuffka, otherwise my administration becomes a mess.

A FourCC error means the 4 character header identifier has an odd value. There can be multple causes for this sympton. It is not a surprise to me that feeding the MPEG-4 parser (m4a) with MPEG (mp3) will data will trigger that error. The file I got from @yimity was a M4A file (I rechecked). That file may be corrupted as the result of an incomplete torrent download, but might as well have a different reason.
